name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/continuous-delivery.yml'
      - 'scripts/sitemapGenerator.mjs'
      - 'package.json'
      - 'yarn.lock'
      - 'Dockerfile'

jobs:
  PublishSkyraPw:
    name: Publish Skyra.pw image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Skyra.pw Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/skyra-project/skyra.pw:latest
